Optimize for build WSA kernels
tiann/KernelSU pull request #1025
Opened 2023-10-10 09:52 UTC by s1204IT

`5.15.104.4` will not be released, so commit internal changes first.

2023-10-12 22:05 UTC, s1204IT commented
@tiann
`5.15.104.4` has finally been released, so please approve and review.

2023-10-13 07:31 UTC, s1204IT commented
And, I'd like the kernel to be include in `v0.6.9` if possible.

2023-10-13 10:10 UTC, tiann requested changes

2023-10-13 10:15 UTC, s1204IT commented on .github/workflows/build-kernel-wsa.yml
> -          if [ ! -z ${{ vars.EXPECTED_SIZE }} ] && [ ! -z ${{ vars.EXPECTED_HASH }} ]; then
https://github.com/tiann/KernelSU/pull/1025/commits/acc7530
Reverted

2023-10-13 11:51 UTC, tiann approved these changes

2023-10-13 11:51 UTC, merged

2023-10-14 08:17 UTC, s1204IT commented
> And, I'd like the kernel to be include in `v0.6.9` if possible.

@tiann 
Is it possible?

2023-10-14 11:57 UTC, tiann commented
> > And, I'd like the kernel to be include in `v0.6.9` if possible.
> 
> @tiann Is it possible?

done