KernelSU: selinux: fix Modules install stuck on kernel 4.4
tiann/KernelSU pull request #1059
Opened 2023-10-19 17:33 UTC by kevios12

This fixes that the Module Installer is stuck when installing any Modules on Kernel 4.4

2023-10-20 00:42 UTC, tiann commented
https://github.com/tiann/KernelSU/issues/1050#issuecomment-1766762513  Does this miss some rules?

2023-10-22 01:23 UTC, tiann requested changes
https://github.com/tiann/KernelSU/issues/1050#issuecomment-1766762513  Does this miss some rules?

2023-10-22 13:46 UTC, kevios12 commented
We added the missing rules to our ROM. Exactly that in the comment

2023-10-22 15:40 UTC, tiann approved these changes

2023-10-22 15:40 UTC, merged