update tr translate
tiann/KernelSU pull request #1108
Opened 2023-11-03 01:36 UTC by Ylarod

2023-11-03 09:59 UTC, Ylarod commented
@mdksec

2023-11-03 13:03 UTC, mdksec commented
I took the english file and translated it. I couldn't find anything else broken except translations

2023-11-03 13:07 UTC, Ylarod commented
> I took the english file and translated it. I couldn't find anything else broken except translations



> I took the english file and translated it. I couldn't find anything else broken except translations

quote is not escaped

2023-11-03 18:41 UTC, symbuzzer reviewed
Many translations are wrong :(

2023-11-03 18:46 UTC, mdksec commented
> Many translations are wrong :(

What's wrong? Tell me and we'll fix it. many places in your translation are in English

2023-11-03 23:20 UTC, dabao1955 commented
Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?

2023-11-04 01:17 UTC, Ylarod commented
> [strings.xml.txt](https://github.com/tiann/KernelSU/files/13251740/strings.xml.txt) I made a few changes, latest

updated

2023-11-04 07:19 UTC, mdksec commented
> Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?

I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad

2023-11-04 07:48 UTC, dabao1955 commented
> > Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?
> 
> I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad

Although, why should I edit all the content from the beginning? Isn't it easier to edit the wrong translation content? And this project is using this method to manage translation instead of submitting [PR](#794) alone(

2023-11-04 07:50 UTC, mdksec commented
> > > Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?
> > 
> > I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad
> 
> Although, why should I edit all the content from the beginning? Isn't it easier to edit the wrong translation content? And this project is using this method to manage translation instead of submitting [PR](https://github.com/tiann/KernelSU/pull/794) alone(

I'm going to edit some parts of the translation in a bit. It's the best translation in the world man

2023-11-04 08:10 UTC, mdksec commented
[strings.xml.txt](https://github.com/tiann/KernelSU/files/13256123/strings.xml.txt)

2023-11-04 11:43 UTC, dabao1955 commented
> > > > Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?
> > > 
> > > 
> > > I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad
> > 
> > 
> > Although, why should I edit all the content from the beginning? Isn't it easier to edit the wrong translation content? And this project is using this method to manage translation instead of submitting [PR](https://github.com/tiann/KernelSU/pull/794) alone(
> 
> I'm going to edit some parts of the translation in a bit. It's the best translation in the world man

Uh-huh, don't you like using weblate for translation?

2023-11-04 11:44 UTC, mdksec commented
> > > > > Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?
> > > > 
> > > > 
> > > > I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad
> > > 
> > > 
> > > Although, why should I edit all the content from the beginning? Isn't it easier to edit the wrong translation content? And this project is using this method to manage translation instead of submitting [PR](https://github.com/tiann/KernelSU/pull/794) alone(
> > 
> > I'm going to edit some parts of the translation in a bit. It's the best translation in the world man
> 
> Uh-huh, don't you like using weblate for translation?

I really don't like the Weblate interface, it is too complicated for me. Crowdin would be better

2023-11-04 11:53 UTC, symbuzzer commented
> > Many translations are wrong :(
> 
> What's wrong? Tell me and we'll fix it. many places in your translation are in English

You translated "superuser" as "yönetici" which means "administrator/manager". In the entire Unix community, superuser means superuser.

What are "Kurtarma Moduna Yeniden Başlat, Önyükleyiciye Yeniden Başlat, İndirme Moduna Yeniden Başlat, EDL Moduna Yeniden Başlat"? Is there such a sentence structure in Turkish?

"KernelSU\'yu nasıl yükleyip modüller kullanacağınızı öğrenin" This sentence is inverted and has a grammatical error.

You should have written "Modülleri sök" instead of "Modülleri çıkart". It could have been much funnier.

I'm sorry my friend, but the translation contains a lot of mistakes like this. I only counted some of them. Please withdraw this PR and let's work together on weblate.

2023-11-04 12:03 UTC, mdksec commented
> > > Many translations are wrong :(
> > 
> > 
> > What's wrong? Tell me and we'll fix it. many places in your translation are in English
> 
> You translated "superuser" as "yönetici" which means "administrator/manager". In the entire Unix community, superuser means superuser.
> 
> What are "Kurtarma Moduna Yeniden Başlat, Önyükleyiciye Yeniden Başlat, İndirme Moduna Yeniden Başlat, EDL Moduna Yeniden Başlat"? Is there such a sentence structure in Turkish?
> 
> "KernelSU'yu nasıl yükleyip modüller kullanacağınızı öğrenin" This sentence is inverted and has a grammatical error.
> 
> You should have written "Modülleri sök" instead of "Modülleri çıkart". It could have been much funnier.
> 
> I'm sorry my friend, but the translation contains a lot of mistakes like this. I only counted some of them. Please withdraw this PR and let's work together on weblate.

ok, you might be right in some places. check the current translation, I think it's the best one for us. change the bad looking parts again and post it here and we'll agree. 

[strings.xml.txt](https://github.com/tiann/KernelSU/files/13256579/strings.xml.txt)

2023-11-04 12:08 UTC, mdksec commented
If this is ok with you, approve and send. It doesn't matter if the translation is still registered in your name.

2023-11-04 12:10 UTC, symbuzzer commented
> If this is ok with you, approve and send. It doesn't matter if the translation is still registered in your name

I think it will be more efficient over Weblate. We cannot see the original text from the XML file. It doesn't matter if the translations are registered in my name. When you translate via Weblate, it is registered in your name.

2023-11-04 12:16 UTC, mdksec commented
> > If this is ok with you, approve and send. It doesn't matter if the translation is still registered in your name
> 
> I think it will be more efficient over Weblate. We cannot see the original text from the XML file. It doesn't matter if the translations are registered in my name. When you translate via Weblate, it is registered in your name.

Let's keep it like this for now. I think the xml file I sent can be saved to weblate and we can continue from there.If you don't approve, your translation can stay. Or leave it like this and add my translations on weblate

2023-11-04 13:09 UTC, dabao1955 commented
> > > > > > Why not try using [weblate](https://hosted.weblate.org/projects/kernelsu/manager/) for translation?
> > > > > 
> > > > > 
> > > > > I had to edit it all from the beginning, so it was easier this way. Once the app is updated, I'll check it again and change anything that looks bad
> > > > 
> > > > 
> > > > Although, why should I edit all the content from the beginning? Isn't it easier to edit the wrong translation content? And this project is using this method to manage translation instead of submitting [PR](https://github.com/tiann/KernelSU/pull/794) alone(
> > > 
> > > 
> > > I'm going to edit some parts of the translation in a bit. It's the best translation in the world man
> > 
> > 
> > Uh-huh, don't you like using weblate for translation?
> 
> I really don't like the Weblate interface, it is too complicated for me. Crowdin would be better

oh

2023-11-05 12:13 UTC, mdksec commented
![strings.xml.txt](https://github.com/tiann/KernelSU/files/13259536/strings.xml.txt)

@Ylarod update please

2023-11-05 13:30 UTC, xiaocenter commented
https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2023-11   已更新内核

2023-11-06 07:48 UTC, symbuzzer commented
@Ylarod Can we clarify whether translations will be via weblate or not?

2023-11-06 07:51 UTC, Ylarod commented
> @Ylarod Can we clarify whether translations will be via weblate or not?

Weblate is recommended, but pr is also accepted personally.
You can move this to weblate and I will close this pr

2023-11-06 07:53 UTC, symbuzzer commented on manager/app/src/main/res/values-tr/strings.xml
> +    <string name="reboot_userspace">Hızlıca yeniden başlat</string>
Hızlı yeniden başlat

2023-11-06 07:55 UTC, symbuzzer commented on manager/app/src/main/res/values-tr/strings.xml
> +    <string name="about_source_code"><![CDATA[Kaynak kodunu görüntüle: %1$s<br/>Bizim %2$s kanalımıza katılın]]></string>
Bizim kanalımıza değil kanalımıza olmalı

2023-11-06 07:56 UTC, symbuzzer commented on manager/app/src/main/res/values-tr/strings.xml
> +    <string name="module_start_downloading">İndirmeye başlanıyor: %s</string>
İndirme başladı olarak kalmalı

2023-11-06 07:58 UTC, symbuzzer commented on manager/app/src/main/res/values-tr/strings.xml
> +    <string name="selinux_status_enforcing">Etkin</string>
Parantez içinde Enforcing yazılabilir.

2023-11-06 07:58 UTC, symbuzzer commented on manager/app/src/main/res/values-tr/strings.xml
> +    <string name="selinux_status_permissive">Boşta</string>
Parantez içinde Permissive yazılabilir.

2023-11-06 08:00 UTC, symbuzzer requested changes
I confirm that it is compatible with the changes I have added as a note. @mdksec

2023-11-06 08:49 UTC, tiann commented
@symbuzzer You can use the "suggest change" feature, it makes us modify it easily:

<img width="802" alt="image" src="https://github.com/tiann/KernelSU/assets/4233744/dbf2f196-f184-4b0b-b90d-35f950141835">

2023-11-07 08:09 UTC, symbuzzer approved these changes
Seems good, thanks for your efforts @mdksec @Ylarod

2023-11-07 09:52 UTC, tiann approved these changes

2023-11-07 09:52 UTC, merged

2023-11-07 10:37 UTC, cachiusa commented
Great, now admins have to go to Weblate and fix the conflict

2023-11-08 04:20 UTC, tiann commented
So that is why we prefer weblate, once you modify the translation both sides, the conflicts will occur.

2023-11-08 06:04 UTC, symbuzzer commented
> @Ylarod Can we clarify whether translations will be via weblate or not?


@tiann I already asked. A few months ago, my translation PR was rejected due to Weblate.