website: update translation
tiann/KernelSU pull request #1322
Opened 2024-01-29 18:42 UTC by igormiguell

2024-01-30 03:07 UTC, tiann requested changes

2024-01-30 03:07 UTC, tiann commented on website/docs/index.md
> +    details: KernelSU allows customization of su, uid, gid, groups, capabilities, and SELinux rules, locking up root privileges.
This changes the meaning

2024-01-30 16:36 UTC, igormiguell commented on website/docs/index.md
> +    details: KernelSU allows customization of su, uid, gid, groups, capabilities, and SELinux rules, locking up root privileges.
fix

2024-01-31 03:16 UTC, tiann approved these changes

2024-01-31 03:16 UTC, merged