Suggest non-gki kernel users to backport path_umount
tiann/KernelSU pull request #1464
Opened 2024-03-17 09:13 UTC by backslashxx

Most kernel builders have to touch their kernel source code anyway, why not also tell them to backport path_umount so even non-gki users can benefit from this?

I know this might be a bit controversial as this will raise the barrier of entry, but the benefits are just so high.

Idea was from OnlyTomInSecond on KernelSU group chat way back, and it has been on the discussions for some time

references:
https://t.me/KernelSU_group/27237/176515
https://t.me/KernelSU_group/3249/184908
https://github.com/tiann/KernelSU/discussions/955#discussioncomment-7617166
https://github.com/OnlyTomInSecond/android_kernel_xiaomi_sdm845/commit/03d233db8bbe9fe101509430bfa09d1899168aa7
https://github.com/tiann/KernelSU/pull/1060 

https://elixir.bootlin.com/linux/v5.9.1/source/fs/namespace.c#L1728
https://elixir.bootlin.com/linux/v5.10.9/source/fs/namespace.c#L1730
https://elixir.bootlin.com/linux/v6.5/source/fs/namespace.c#L1887 https://github.com/tiann/KernelSU/pull/1464#issuecomment-2002492107

Kernel side change examples
5.4 https://github.com/natsumerinchan/kernel_oneplus_sm8350/commit/961d9788624e88c3c58918b3781b9fbdd19ecbeb 
4.19 https://github.com/backslashxx/android_karnol_ximi_fog/commit/164917f56d0e75ab51bb9f1bdf489acac7a6d3db
4.14 https://github.com/crdroidandroid/android_kernel_xiaomi_sm6150/commit/c07c70a0c59fb46ac0c1c812c3e993022e375cd5
4.9 https://github.com/backslashxx/msm8953-los21/commit/195f07593ae9769a992f3945bcdc43ff7fc99827
4.4 https://github.com/riarumoda/android_kernel_samsung_a9y18qlte/commit/21ea33fe41ce079ec1d663c0bd2201bc00a8084a https://github.com/tiann/KernelSU/pull/1464#issuecomment-2002424069
ofcourse having someone on 3.18 confirm this will be nice.

**PROS**: umount modules for everyone
**CONS**: barrier of entry +1

2024-03-17 10:07 UTC, Asyanx commented
+1 work

2024-03-17 10:08 UTC, xennin commented
pro

2024-03-17 10:12 UTC, Fede2782 commented
+1. It could really  uniform things up. I can confirm works on my 4.9 and 4.14

2024-03-17 10:13 UTC, alternoegraha commented
+1

2024-03-17 10:17 UTC, Dwyor-tmx commented
+1 work on my kramel 😋

2024-03-17 10:18 UTC, Dwyor-tmx commented
+1 work on my kramel 😋

2024-03-17 10:20 UTC, Dwyor-tmx commented
+1

2024-03-17 10:21 UTC, Dwyor-tmx commented
> Most kernel builders have to touch their kernel source code anyway, why not also tell them to backport path_umount so even non-gki users can benefit from this?
> 
> I know this might be a bit controversial as this will raise the barrier of entry, but the benefits are just so high.
> 
> Idea was from OnlyTomInSecond on KernelSU group chat way back, and it has been on the discussions for some time
> 
> references: https://t.me/KernelSU_group/27237/176515 https://t.me/KernelSU_group/3249/184908 [#955 (comment)](https://github.com/tiann/KernelSU/discussions/955#discussioncomment-7617166) [OnlyTomInSecond/android_kernel_xiaomi_sdm845@03d233d](https://github.com/OnlyTomInSecond/android_kernel_xiaomi_sdm845/commit/03d233db8bbe9fe101509430bfa09d1899168aa7)
> 
> Kernel side change examples 5.4 [dev-sm8350/kernel_oneplus_sm8350@40fe07b](https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/40fe07bbc851b50c204c6a91128b5cbefb7a6296) [natsumerinchan/kernel_oneplus_sm8350@961d978](https://github.com/natsumerinchan/kernel_oneplus_sm8350/commit/961d9788624e88c3c58918b3781b9fbdd19ecbeb) 4.19 [backslashxx/android_karnol_ximi_fog@164917f](https://github.com/backslashxx/android_karnol_ximi_fog/commit/164917f56d0e75ab51bb9f1bdf489acac7a6d3db) 4.14 [backslashxx/mojito_krenol@686e90b](https://github.com/backslashxx/mojito_krenol/commit/686e90b6a63ad0851e964bddab7add54ec52b973) 4.9 [backslashxx/msm8953-los21@195f075](https://github.com/backslashxx/msm8953-los21/commit/195f07593ae9769a992f3945bcdc43ff7fc99827) ofcourse having someone on a 4.4 kernel confirm this will be nice.
> 
> TL;DR PROS: umount modules for everyone CONS: barrier of entry +1

+1 Work on my kramel 😋

2024-03-17 10:21 UTC, Dwyor-tmx commented
+1

2024-03-17 10:32 UTC, privacyguy123 commented
+1

2024-03-17 10:40 UTC, Fede2782 commented
@backslashxx I don't know if there is a way to do this but the best way would be to dynamically enable/disable modules umount feature if there is the path_umount code in fs/namespace.c, because very likely @tiann will close this issue as he did with the other one

2024-03-17 11:28 UTC, FerryAr commented
+1

2024-03-17 11:42 UTC, riarumoda commented
Hi, 4.4 kernel user in here, i used the 4.9 patch and it works. my messy commit is in here:
https://github.com/riarumoda/android_kernel_samsung_a9y18qlte/commit/046ec1c9482a4b6828e112dcfd2966d1cd765129
https://github.com/riarumoda/android_kernel_samsung_a9y18qlte/commit/d370283ea8744cdb989d786404cd3acc6237bb44
https://github.com/riarumoda/android_kernel_samsung_a9y18qlte/commit/21ea33fe41ce079ec1d663c0bd2201bc00a8084a

2024-03-17 11:51 UTC, Fede2782 commented
> > @backslashxx I don't know if there is a way to do this but the best way would be to dynamically enable/disable modules umount feature if there is the path_umount code in fs/namespace.c, because very likely @tiann will close this issue as he did with the other one
> 
> is there a way to test a function if it exists before linking? if so then thats a plausible way to do it.

I would say to make that little part of code separated and it could be built or not by a Makefile statement if it locates the code in fs/namespace.c. I will try to implement this if i have time in these days

2024-03-17 12:15 UTC, Fede2782 commented
> > I would say to make that little part of code separated and it could be built or not by a Makefile statement if it locates the code in fs/namespace.c. I will try to implement this if i have time in these days if it is possible
> 
> Good idea. --check latest change I continue with #error warning and still forcing builder to do it, or of course, do nothing?? b-b-b-but I want everyone to do it bruv

Yes i think it could work, good job. I'll try to build later and see if works. In any case you should not force this change i think. Let the devs choose

2024-03-17 12:44 UTC, Fede2782 commented
I would prefer to use something like this but i am not sure. 
```c
static void ksu_umount_mnt(struct path *path, int flags)
{
#ifdef KSU_UMOUNT
	int err = path_umount(path, flags);
	if (err) {
		pr_info("umount %s failed: %d\n", path->dentry->d_iname, err);
	}
#else
	// TODO: umount for non GKI kernel
        #warning Did you know you can backport path_umount to fs/namespace.c from 5.9?
        #warning https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#backport-path_umount-from-linux-59

#endif
}
```

2024-03-17 13:12 UTC, Fede2782 requested changes
Really good idea

2024-03-17 13:12 UTC, Fede2782 commented on website/docs/guide/how-to-integrate-for-non-gki.md
> +```
You should add "diff" in the start of the code block and explain why is required. Maybe also write in the KPROBES section and manual edit section to read the backport path umount part

```
In order to make a more standard KernelSU implementation, you should backport the ```code_umount``` feature in ```fs/namespace.c``` if your kernel version is 5.9 or lower. Here is a patch to refer:

```[diff]
--- a/fs/namespace.c
+++ b/fs/namespace.c
@@ -1739,6 +1739,39 @@ static inline bool may_mandlock(void)
 }
 #endif
 
+static int can_umount(const struct path *path, int flags)
+{
+	struct mount *mnt = real_mount(path->mnt);
+
+	if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))
+		return -EINVAL;
+	if (!may_mount())
+		return -EPERM;
+	if (path->dentry != path->mnt->mnt_root)
+		return -EINVAL;
+	if (!check_mnt(mnt))
+		return -EINVAL;
+	if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */
+		return -EINVAL;
+	if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))
+		return -EPERM;
+	return 0;
+}
+
+int path_umount(struct path *path, int flags)
+{
+	struct mount *mnt = real_mount(path->mnt);
+	int ret;
+
+	ret = can_umount(path, flags);
+	if (!ret)
+		ret = do_umount(mnt, flags);
+
+	/* we mustn't call path_put() as that would clear mnt_expiry_mark */
+	dput(path->dentry);
+	mntput_no_expire(mnt);
+	return ret;
+}
 /*
  * Now umount can handle mount points as well as block devices.
  * This is important for filesystems which use unnamed block devices.
```

2024-03-17 13:21 UTC, Fede2782 approved these changes

2024-03-17 13:50 UTC, tiann requested changes

2024-03-17 13:50 UTC, tiann commented on kernel/Makefile
> +endif
Add the warning here.

2024-03-17 13:50 UTC, tiann commented on kernel/core_hook.c
> -#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 9, 0)
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 9, 0) || if defined(XXX)

This way it will never break gki.

2024-03-17 13:50 UTC, tiann commented on kernel/core_hook.c
> +	#warning Did you know you can backport path_umount to fs/namespace.c from 5.9?
Remove this because the makefile will warn it.

2024-03-17 13:50 UTC, tiann commented on kernel/setup.sh
> +grep -q "int path_umount" fs/namespace.c || echo "Did you know you can backport path_umount to fs/namespace.c from 5.9? Read: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#backport-pat
If you add the warning to Makefile, this can be removed.

2024-03-17 13:58 UTC, tiann commented
> ready to squash I guess. I'll squash after another approving review

You don't need to squash, i will make a squash merge.

2024-03-17 14:32 UTC, chiteroman commented
+1 but why don't use latest code ?

https://elixir.bootlin.com/linux/latest/A/ident/path_umount

```cpp
/**
 * path_mounted - check whether path is mounted
 * @path: path to check
 *
 * Determine whether @path refers to the root of a mount.
 *
 * Return: true if @path is the root of a mount, false if not.
 */
static inline bool path_mounted(const struct path *path)
{
	return path->mnt->mnt_root == path->dentry;
}

static int can_umount(const struct path *path, int flags)
{
	struct mount *mnt = real_mount(path->mnt);

	if (!may_mount())
		return -EPERM;
	if (!path_mounted(path))
		return -EINVAL;
	if (!check_mnt(mnt))
		return -EINVAL;
	if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */
		return -EINVAL;
	if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))
		return -EPERM;
	return 0;
}

// caller is responsible for flags being sane
int path_umount(struct path *path, int flags)
{
	struct mount *mnt = real_mount(path->mnt);
	int ret;

	ret = can_umount(path, flags);
	if (!ret)
		ret = do_umount(mnt, flags);

	/* we mustn't call path_put() as that would clear mnt_expiry_mark */
	dput(path->dentry);
	mntput_no_expire(mnt);
	return ret;
}
```

2024-03-17 18:01 UTC, Fede2782 commented
> Is this attention grabbing enough? ![image](https://private-user-images.githubusercontent.com/118538522/313492334-fd5f4b2f-2f46-4202-b874-c6f6172e58de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTg2NjksIm5iZiI6MTcxMDY5ODM2OSwicGF0aCI6Ii8xMTg1Mzg1MjIvMzEzNDkyMzM0LWZkNWY0YjJmLTJmNDYtNDIwMi1iODc0LWM2ZjYxNzJlNThkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxNzU5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjJhOGZjNWVlYzdhOTE4ZTU4ZTU2MThkOGFlMTQ0OGEwNWIwODRlZDg2NjE3OTNiY2M1MmMxYmU1ZTkzNjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TDm-Q6xChbX7gKe0h3EgtTVY6a-zhsjuQYfZGDBE2XM)
> 
> The thing is, the normal output is not even noticeable.

I would not waste time on this. Just write clearly in release notes and in the documentation (must be written clearly in both sections: krpobes and manual) and developers will notice. If some dev doesn't read the users will very likely complain to him and will implementation asap

2024-03-17 18:25 UTC, Fede2782 commented
For the docs i think is more coherent  this https://github.com/Fede2782/KernelSU/blob/main/website/docs/guide/how-to-integrate-for-non-gki.md

2024-03-17 19:25 UTC, ExtremeXT commented
+1

2024-03-17 22:57 UTC, Zerototheleft122105 commented
Todo lo que proponéis me resulta complicado Pero llegará el momento de que lo domine. Un gran +1

2024-03-18 01:35 UTC, tiann requested changes

2024-03-18 01:35 UTC, tiann commented on kernel/Makefile
> +
please remove this noisy

2024-03-18 01:35 UTC, tiann commented on kernel/Makefile
> +$(info -- Read: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#path_umount)
I don't want to open this file every time and see that most of the content is useless to me. Keep it simple please, one line is enough.

2024-03-18 01:57 UTC, tiann approved these changes

2024-03-18 02:27 UTC, merged

2026-08-06 03:42 UTC, nndmt034 approved these changes