kernel, ksud: collect binaries into /data/adb/ksu
tiann/KernelSU pull request #161
Opened 2023-01-31 07:53 UTC by skbeh

2023-01-31 11:09 UTC, tiann commented
When the directory is created? `/data/adb` is created by Android, if you use its subdirectory, you should create it.

2023-01-31 13:06 UTC, skbeh commented
> When the directory is created? `/data/adb` is created by Android, if you use its subdirectory, you should create it.

It is created before usage.

2023-01-31 15:22 UTC, tiann requested changes

2023-01-31 15:47 UTC, skbeh commented on kernel/allowlist.c
> +#define KERNEL_SU_ALLOWLIST "/data/adb/ksu/allowlist"
I think that the one who wants to delete it will delete it anyway, and magisk doesn't use hidden file.

2023-02-01 01:03 UTC, tiann commented
I will test it with my device later

2023-02-01 02:44 UTC, tiann commented
Please keep `/data/adb/ksud` the same, this command is useful for developers, we don't like to type more words.
Other modification is OK.

2023-02-01 02:46 UTC, skbeh commented
> Please keep `/data/adb/ksud` the same, this command is useful for developers, we don't like to type more words. Other modification is OK.

Would you like to move it to somewhere in `PATH`?

2023-02-01 02:49 UTC, skbeh commented
Or we can modify `PATH` for the commands which are executed by `su`.

2023-02-01 02:50 UTC, tiann commented
> > Please keep `/data/adb/ksud` the same, this command is useful for developers, we don't like to type more words. Other modification is OK.
> 
> Would you like to move it to somewhere in `PATH`?

We don't want to put it in $PATH, it is an internal implementation, not an API.

2023-02-01 02:57 UTC, skbeh commented
Would you like to ship `busybox` to gain some compatibility with magisk?

2023-02-01 03:26 UTC, tiann commented
> Would you like to embed `busybox` to gain some compatibility with magisk?

we should do that

2023-02-01 04:34 UTC, skbeh commented
@tiann BusyBox is licensed under GPLv2, so embedding it breaks the license. Also the linux kernel is licensed under GPLv2, so linking kernelsu with it also breaks license.

2023-02-01 04:35 UTC, skbeh commented
I suggest to license kernelsu under GPLv2 or GPLv2-or-later.

2023-02-01 04:48 UTC, tiann commented
KernelSU is GPL-3

2023-02-01 04:50 UTC, skbeh commented
> KernelSU is GPL-3

GPLv3 is not compatible with GPLv2.

2023-02-01 04:52 UTC, tiann commented
Magisk is also GPL3

2023-02-01 04:53 UTC, skbeh commented
> Magisk is also GPL3

Because magisk doesn't link with Linux kernel or GPLv2 libraries.

2023-02-01 05:01 UTC, tiann commented
GPLv2-or-later should be Ok？Magisk is GPL3 and we use its reserprop

2023-02-01 05:07 UTC, skbeh commented
> GPLv2-or-later should be Ok

I think it should be. However, I am not a lawyer, so I can not give legal advices.

2023-02-01 07:28 UTC, tiann commented
I consulted the layer, kernel is gpl2 without later, so the kernel part of KernelSU must be gpl2 without later.
So, I will relicense it under gpl2.

2023-02-01 08:31 UTC, skbeh commented
The binaries are directly taken from Magisk v25.2 apk.

2023-02-01 08:45 UTC, tiann requested changes

2023-02-01 09:07 UTC, skbeh commented on userspace/ksud/src/defs.rs
> +pub const DAEMON_PATH: &str = concatcp!(WORKING_DIR, "ksud");
Why?

2023-02-01 09:16 UTC, tiann commented on userspace/ksud/src/defs.rs
> +pub const DAEMON_PATH: &str = concatcp!(WORKING_DIR, "ksud");
it is `/data/adb/ksu/ksud` but `/data/adb/ksud` in kernel

2023-02-01 09:27 UTC, skbeh commented on userspace/ksud/src/event.rs
> +    ensure_dir_exists(dst)?;
It should be checked in case `/data/adb` is deleted.

2023-02-01 09:37 UTC, tiann approved these changes

2023-02-01 09:58 UTC, merged