fix #1559
tiann/KernelSU pull request #1633
Opened 2024-04-15 12:45 UTC by TinyHai

这个问题早些天我就遇到过，不过没怎么细究，今天又遇到了，就花了点时间捣鼓了一下。

一开始有点懵，好好的为什么会突然获取root失败。直到我`ps -A | grep <kernelsu pid>`看到一连十几个`sh`子进程，但没有一个是root进程，接着又花了点时间找复现方法，最终

复现步骤:
- 首先打开KernelSU
- 在首页和其他页之间来回切
- 通过`ps -A | grep <kernelsu pid>`可以发现，会出现一堆子进程，其中会有两个是root进程
- 继续在首页和其他页之间来回切
- 再执行`ps -A | grep <kernelsu pid>`, root进程消失了，应该是被系统杀了
- KernelSU首页弹出获取root失败

我感觉这样处理有点粗糙，应该将shell获取规范一下，而不是哪哪都创建一个。术哥怎么看 :P

2024-04-15 13:24 UTC, tiann commented
这个问题的原因应该是 root 进程过多，触发幽灵进程限制导致第一个 root shell 被杀，https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt#L294 此处返回了 false；
应该把 root 状态缓存起来，而不是每次都去获取。

至于每次都创建一个新进程，这应该是预期行为，如果用缓存，难免会遇到上述问题；另外，如果公用一个 shell，只要有一个人阻塞了这个shell，其他人都无法调用成功。

webui 不应该全局缓存，否则如果有人执行后台任务，其他模块调用 webapi 都会阻塞无法返回。

2024-04-15 13:35 UTC, TinyHai commented
> 这个问题的原因应该是 root 进程过多，触发幽灵进程限制导致第一个 root shell 被杀，https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt#L294 此处返回了 false；
> 应该把 root 状态缓存起来，而不是每次都去获取。
> 
> 至于每次都创建一个新进程，这应该是预期行为，如果用缓存，难免会遇到上述问题；另外，如果公用一个 shell，只要有一个人阻塞了这个shell，其他人都无法调用成功。
> 
> webui 不应该全局缓存，否则如果有人执行后台任务，其他模块调用 webapi 都会阻塞无法返回。

那为了避免创建太多的shell，应该在shell用完后及时关闭。有没有比较优雅的处理方式

2024-04-15 13:56 UTC, tiann commented
调用 shell 的 close 试试？

2024-04-15 14:30 UTC, TinyHai commented
> 调用 shell 的 close 试试？

其实我想问的是要怎么让这些创建出来的shell在不被需要的时候能及时调用close，一看这回答就知道术哥没有e认真review我提交的代码

2024-04-15 14:50 UTC, tiann commented
你可以试试用 PhantomReference 在 shell 被 gc 时调用 close，看能否解决问题

2024-04-15 17:32 UTC, TinyHai commented
> 你可以试试用 PhantomReference 在 shell 被 gc 时调用 close，看能否解决问题

按照你说的尝试了一下，不过由于幽灵引用没法拿到gc后的对象，所以我在shell创建后先把pid保存下来，等shell被回收后通过pid来kill掉对应的shell进程。不知道这样是否会有f问题

2024-04-16 01:56 UTC, tiann commented
这样的话手动 close 更好

2024-04-16 02:11 UTC, TinyHai commented
> 这样的话手动 close 更好

看来到最后还得是手动档，不过能具体说说这样写有哪些问题吗

2024-04-16 02:49 UTC, TinyHai commented
> 哪样写？你最新的做法引来了额外的复杂度，没有必要

那就是说，目前最简单的处理方式就是在所有调用`createRootShell`的地方用完后手动调用一下`close`, 对吧

2024-04-16 03:15 UTC, tiann commented
是的

2024-04-16 12:17 UTC, tiann requested changes

2024-04-16 12:17 UTC, tiann commented on manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt
> +import okhttp3.internal.closeQuietly
it is not good to import other's internal func

2024-04-16 12:59 UTC, tiann approved these changes

2024-04-16 14:02 UTC, merged