manager: 添加禁止默认修补init_boot的开关
tiann/KernelSU pull request #1744
Opened 2024-05-19 06:27 UTC by HDTianRu

有一些设备（如ace2v），带了initboot，但ramdisk却在boot里，导致无法使用ota安装与直接安装，所以添加了个开关
因为本人开发环境有点简陋(mt管理器)，而且对项目代码不太熟，合并前最好review一下（

2024-05-19 07:26 UTC, tiann commented
你的设备 `ace2v` 内核具体版本号是多少？

2024-05-19 14:02 UTC, HDTianRu commented
> 你的设备 `ace2v` 内核具体版本号是多少？

一加ACE 2V
内核版本5.10.198-android12-9
coloros14.0，安卓版本14
系统有init_boot.img
但需要修补boot.img
如直接在管理器进行直接安装或ota安装，会自动选择修补init_boot，导致修补失败，报错退出
![管理器界面](https://github.com/tiann/KernelSU/assets/103573273/e50924bf-395b-4b90-92bd-c8db885a7ba2)
![直接安装](https://github.com/tiann/KernelSU/assets/103573273/c8d82bd8-d61e-490e-873f-08d037d5c527)

2024-05-20 02:40 UTC, tiann commented
我认为这种实现方法更好：如果存在 init_boot 分区，但内核版本为 `android12-xxxx` 那么依然选择 boot 分区，不需要用户去干预。目前遇到的几个设备都是这样的。

2024-05-20 14:54 UTC, HDTianRu commented
> 我认为这种实现方法更好：如果存在 init_boot 分区，但内核版本为 `android12-xxxx` 那么依然选择 boot 分区，不需要用户去干预。目前遇到的几个设备都是这样的。

我感觉有init_boot分区但需要修补boot分区的抽象设备只是少数，可能还有部分用户是 `android12-xxxx` 内核且需要正常修补 `init_boot` 分区，单纯以内核版本判断可能出现新的问题，毕竟因为在正常设备上，管理器可以正常工作，所以他们并不会反馈问题

2024-05-20 14:58 UTC, HDTianRu commented
或者我觉得可以先尝试修补 `init_boot` 分区，解包失败发现没有 `ramdisk` 且为 `android12-xxxx` 内核后尝试修补 `boot` 分区

2024-05-21 01:19 UTC, tiann commented
android12-xxx 绝大部分都是修补 boot 分区，有 init_boot 分区的是极少数，这个逻辑并不会影响到它们。

2024-05-21 15:10 UTC, HDTianRu commented
好了，希望不会伤害到任何人（）

2024-05-23 01:43 UTC, tiann approved these changes

2024-05-23 03:09 UTC, tiann requested changes
请修复一下格式问题

2024-05-25 03:09 UTC, tiann approved these changes

2024-05-25 03:09 UTC, merged