fix translation
tiann/KernelSU pull request #244
Opened 2023-02-14 16:29 UTC by reindex-ot

Japanese Translation Adjustments and Fixes

2023-02-15 03:39 UTC, tiann commented
Please resolve the conflicts

2023-02-19 16:40 UTC, reindex-ot commented
resolved.

2023-02-20 02:39 UTC, tiann requested changes

2023-02-20 02:39 UTC, tiann commented on manager/app/src/main/res/values-ja/strings.xml
> +  <string name="home_version">バージョン</string>
This should be `home_manager_version`

2023-02-20 11:20 UTC, reindex-ot commented on manager/app/src/main/res/values-ja/strings.xml
> +  <string name="home_version">バージョン</string>
sorry...fixed.

2023-02-20 11:37 UTC, tiann commented
Thanks for your contribution!

2023-02-20 11:37 UTC, tiann approved these changes

2023-02-20 11:37 UTC, merged