make huawei hi6520 4.9.319 kernel compile
tiann/KernelSU pull request #431
Opened 2023-04-24 12:11 UTC by Abdelhay-Ali

2023-04-24 17:20 UTC, PaperStrike commented
~hi6520~ hi6250 right?
And 4.x.256+ `LINUX_VERSION_CODE` differs with their `KERNEL_VERSION` (https://github.com/tiann/KernelSU/pull/401#issue-1674516307), I suggest

```diff
- 	LINUX_VERSION_CODE <= KERNEL_VERSION(4, 9, 319)
+ 	LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
```

for better semantics while keeping the same behavior.

2023-04-26 03:46 UTC, tiann requested changes

2023-04-26 19:00 UTC, Abdelhay-Ali commented on kernel/selinux/sepolicy.c
> +	LINUX_VERSION_CODE <= KERNEL_VERSION(4, 9, 319)
Yes, we can. The kernel compile without problem using KERNEL_VERSION(4, 10, 0)

2023-04-27 05:29 UTC, tiann approved these changes

2023-04-27 05:30 UTC, merged