setup.sh:change "obj-y"to"obj-$(CONFIG_KSU)" and add KernelSU in drivers/Kconfig
tiann/KernelSU pull request #582
Opened 2023-06-04 01:37 UTC by dabao1955

#570

2023-06-04 10:25 UTC, dabao1955 commented
Could it be that the priority of this PR is too low?

2023-06-05 01:26 UTC, tiann commented
What if someone add `\n` to the end of the origin Kconfig?

2023-06-05 04:35 UTC, tiann requested changes
If someone modifies Kconfig and endmenu is not placed on the last line, compilation will fail. I suggest identifying the line where endmenu is located and inserting the required code before it.

2023-06-05 05:00 UTC, dabao1955 commented
> If someone modifies Kconfig and endmenu is not placed on the last line, compilation will fail. I suggest identifying the line where endmenu is located and inserting the required code before it.

I added this line to the penultimate line of drivers/Kconfig. Generally, the penultimate line usually ends with endmemu. I can add to the fourth line instead of the penultimate line if that matters.

Or I have another solution: add kernelsu item to arch/arm64/Kconfig. But if you do this, you can only find the kernelsu tab in the main menu instead of the Device drivers tab.

![Screenshot_2023-06-05-13-00-20-34_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/tiann/KernelSU/assets/79307765/fdec424e-c269-4960-ba95-c78bc67255c1)

2023-06-05 05:01 UTC, dabao1955 commented
> What if someone add `\n` to the end of the origin Kconfig?

Which line is it in?

2023-06-05 05:04 UTC, dabao1955 commented
> > What if someone add `\n` to the end of the origin Kconfig?
> 
> Which line is it in?

If it's the forty-eighth line, it breaks the aesthetics if you don't add the \n. It is also to prevent certain Kconfig from being overwritten. Although I haven't encountered this situation.![Screenshot_2023-06-05-13-03-47-19_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/tiann/KernelSU/assets/79307765/b481ffd1-4128-43ce-a5dd-d17498b00396)

2023-06-05 05:26 UTC, tiann commented
我的意思是说，如果有人手动改了 Kconfig 文件，不小心在文件的最末尾加了几个回车，这还能工作吗？

2023-06-05 05:30 UTC, dabao1955 commented
> 我的意思是说，如果有人手动改了 Kconfig 文件，不小心在文件的最末尾加了几个回车，这还能工作吗？

理论上来说应该是会工作的？至少make menuconfig会。
除非是格式错误或者soucrce的文件不存在。

2023-06-05 05:34 UTC, dabao1955 commented
> > 我的意思是说，如果有人手动改了 Kconfig 文件，不小心在文件的最末尾加了几个回车，这还能工作吗？
> 
> 理论上来说应该是会工作的？至少make menuconfig会。
> 除非是格式错误或者source的文件不存在，这样Makefile会报错
> 
> ```
> drivers/Kconfig:242:warning: ignoring unsupported character '/'
> drivers/Kconfig:242:warning: ignoring unsupported character '/'
> drivers/Kconfig:242:warning: ignoring unsupported character '"'
> drivers/Kconfig:242: invalid statement
> drivers/Kconfig:244: unexpected end statement
> make[1]: *** [scripts/kconfig/Makefile:29：menuconfig] 错误 1
> make: *** [Makefile:589：menuconfig] 错误 2
> ```
> 
> 或
> ```
> drivers/Kconfig:242: can't open file "drivers/kernelsu/kconfig"
> ```

我建议还是扔在arch/arm64/Kconfig里。那里没有endmenu

2023-06-05 05:36 UTC, tiann commented
扔 arch/arm64/Kconfig，x86_64 还能工作吗？

2023-06-05 05:38 UTC, dabao1955 commented
> 扔 arch/arm64/Kconfig，x86_64 还能工作吗？

抱歉是我考虑不周了。我还在想一个稳妥的办法。
例如扔到drivers/Kconfig的第四行

2023-06-05 05:40 UTC, dabao1955 commented
> > 扔 arch/arm64/Kconfig，x86_64 还能工作吗？
> 
> 抱歉是我考虑不周了。我还在想一个稳妥的办法。
> 例如扔到drivers/Kconfig的第四行

![Screenshot_2023-06-05-13-39-32-43_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/tiann/KernelSU/assets/79307765/bdc6a91a-7191-4ad3-adbc-03cd024c601e)

扔在内核目录的Kconfig怎么样？

2023-06-05 10:16 UTC, tiann commented
如果 `menu` 在第四行之后呢？？

如果你想不出更好的办法，就用我的方案，不要浪费别人时间。

2023-06-05 10:19 UTC, dabao1955 commented
> 如果 `menu` 在第四行之后呢？？
> 
> 如果你想不出更好的办法，就用我的方案，不要浪费别人时间。

我看了Kconfig，menu在第二行。

2023-06-05 10:21 UTC, tiann commented
为什么你觉得别人不会在那里加几行注释？

2023-06-05 10:23 UTC, dabao1955 commented
> 为什么你觉得别人不会在那里加几行注释？

那扔在内核根目录下的Kconfig行不？

2023-06-05 10:35 UTC, dabao1955 commented
对不起，我为我自己鲁莽的行为感到抱歉。
事实上，您说的确实有道理。
我的解决办法是在最后一行[endmenu]之前插入source "drivers/kernelsu/Kconfig"。
这样继能在menuconfig里开关kernelsu，又不会因此报错。

2023-06-05 11:15 UTC, closed without merging