update
tiann/KernelSU pull request #596
Opened 2023-06-05 13:34 UTC by linuxyyds666

Hello, I'm a newcomer. Recently I found that I couldn't open kernelsu debug mode when compiling the kernel, and I tried modifying the script according to the new bing's prompt. It  looks working fine.

2023-06-05 13:44 UTC, tiann requested changes

2023-06-05 13:44 UTC, tiann commented on kernel/setup.sh
> +grep -q "kernelsu" drivers/Kconfig || sed -i '/endmenu/i source "drivers/kernelsu/Kconfig"' drivers/Kconfig
Please use $DRIVER_DIR instead of hardcode it

2023-06-05 14:03 UTC, tiann commented
By the way, you can add `ccflags-y += -DCONFIG_KSU_DEBUG` to Makefile to enable debug mode if you don't want to change config.

2023-06-05 14:09 UTC, tiann commented
this means using "$DRIVER_DIR" instead, not $(DRIVER_DIR) or $DRIVER_DIR, you can ask new bing or chatgpt

2023-06-05 14:11 UTC, linuxyyds666 commented
> this means using "$DRIVER_DIR" instead, not $(DRIVER_DIR) or $DRIVER_DIR, you can ask new bing or chatgpt

OK.

2023-06-06 03:40 UTC, tiann requested changes

2023-06-06 04:12 UTC, closed without merging