CI: Add ARCVM to release and Support set manager signature size and hash
tiann/KernelSU pull request #757
Opened 2023-07-12 09:15 UTC by natsumerinchan

https://github.com/tiann/KernelSU/issues/739
https://github.com/tiann/KernelSU/issues/745
https://github.com/tiann/KernelSU/issues/752

2023-07-12 09:20 UTC, natsumerinchan commented
变量在Repository variables设置

![截图 2023-07-12 17-18-32](https://github.com/tiann/KernelSU/assets/64072399/f88655b5-4318-40db-b3ce-a8f6427d0871)

2023-07-13 11:26 UTC, tiann commented
请把这两个功能区分为单独的 pr

2023-07-13 12:04 UTC, natsumerinchan commented
> 请把这两个功能区分为单独的 pr

ok稍等

2023-07-13 12:20 UTC, natsumerinchan commented
已完成

2023-07-18 01:41 UTC, tiann commented
Makefile 中应该是可以直接使用环境变量的，不需要再重新定义一个。

2023-07-18 01:42 UTC, tiann requested changes

2023-07-18 02:08 UTC, natsumerinchan commented on kernel/Makefile
> +EXPECTED_SIZE := $(shell echo "$KSU_EXPECTED_SIZE")
直接使用$KSU_EXPECTED_HASH就足够了
```
-- KernelSU version: 11117
-- KernelSU Manager signature size: 0x352
-- KernelSU Manager signature hash: 0x4798d2cf
```

2023-07-18 02:10 UTC, tiann approved these changes

2023-07-18 04:38 UTC, merged